export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const BOOKS_LIST_CLEAR_MESSAGE = "BOOKS_LIST_CLEAR_MESSAGE";

export const AUTH_STORE_TOKEN = "AUTH_STORE_TOKEN";
